---
- name: configure customer VLAN  on all switches
  connection: local
  gather_facts: False
  hosts: switches
  vars_files:
  - creds.yml
  - "{{custfile}}"

  tasks:
  - name: configure provider
    set_fact:
      provider:
        username: "{{username}}"
        password: "{{password}}"
        host: "{{inventory_hostname}}"
        
  - name: configure edge ports
    ios_config:
      provider: "{{provider}}"
      lines:
      - switchport trunk allowed vlan add {{vlan}}
      parents:
      - interface {{item.port}}
    with_items: "{{edgeports}}"
    when: (item.sw == inventory_hostname)

  - name: enable trunk encapsulation
    ios_config:
      provider: "{{provider}}"
      lines:
      - switchport trunk encapsulation dot1q
      - switchport mode trunk
      - switchport trunk allowed vlan all
      - description work done by ansible automation
      - no shutdown
      parents:
      - interface {{'FastEthernet 0/12'}}
               
  - name: configure core trunk ports
    ios_config:
      provider: "{{provider}}"
      lines:
      - switchport trunk allowed vlan add {{vlan}}
      parents:
      - interface {{item.port}}
    with_items: "{{coretrunks}}"
    when: (item.sw == inventory_hostname)

  - name: create vlan
    ios_config:
      provider: "{{provider}}"
      lines:
      - name {{customername}}
      parents:
- vlan {{vlan}}